In [1]:
# 4.1 Games of Chance
import random
# A. Simulate flipping a coin 100 times, then print the percentage of results that were "heads"

In [2]:
# B. Randomly choose an element until you choose "yellow", incrememting flips each time
#    Print a message each time including how many flips have been executed and what the result was
flips = 0
sides = ["blue", "blue", "blue", "blue", "yellow", "blue"]

In [3]:
# C. Simulate a slot machine with the following rules:
#    i. Each turn, the player loses 1 point and three random elements are chosen
#    ii. If the three elements are all the same, the player wins 2 points
#    iii. If all three elements are different, the player wins 5 points
#    Continue taking turns until the player has 0 points or more than 10 points
#    Each turn, print a message describing the outcome of the machine
elements = ["red", "green", "blue"]
player_points = 7

In [36]:
# 4.2 EDA Demonstration
import pandas as pd
%matplotlib inline

In [37]:
# We will store the orders table csv data in a variable
# Tabs are used as the separating character in this file

# tabs are used as separators, so we use "\t"
orders = pd.read_csv("orders.csv", sep="\t")

In [38]:
# Use the head method to investigate the first row of data

orders.head(1)

  order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id
0  CA-2016-2608109,17/09/2016 00:00,17/09/2016 00...

In [39]:
# Create a dataframe to view the column names and data types

import pandas as pd

pd.DataFrame(orders.dtypes, columns=["DataType"])

                                                   DataType
order_id,order_date,ship_date,ship_mode,custome...      str

In [40]:
# Use the shape attribute to determine the amount of rows and columns total

orders.shape

(990677, 1)

In [41]:
# Use the .columns property to list out the column names
orders.columns

# Use the .index.name property to identify the index
orders.index.name

print(orders.columns)
print(orders.index.name)

Index(['order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id'], dtype='str')
None

In [43]:
# Provide a dictionary to the rename method to rename any columns
# The inplace flag determines whether to modify the original dataframe

orders.rename(columns={"old_name": "new_name"}, inplace=True)

print(orders.columns)
orders.head()

Index(['order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id'], dtype='str')

  order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id
0  CA-2016-2608109,17/09/2016 00:00,17/09/2016 00...
1  ES-2018-1945518,29/08/2018 00:00,02/09/2018 00...
2  ES-2018-853948,28/07/2018 00:00,29/07/2018 00:...
3  ES-2019-1912507,01/04/2019 00:00,05/04/2019 00...
4  ES-2019-2038080,25/03/2019 00:00,28/03/2019 00...

In [44]:
# Explore columns with column attributes and methods

# show all column names
orders.columns

# show data types of each column
orders.dtypes

# detailed summary of the dataset
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 990677 entries, 0 to 990676
Data columns (total 1 columns):
 #   Column                                                                                                               Non-Null Count   Dtype
---  ------                                                                                                               --------------   -----
 0   order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id  990677 non-null  str
dtypes: str(1)
memory usage: 7.6 MB

In [ ]:
# 4.3 Exploring a new dataset
# Import the products.csv dataset and explore the following questions:

In [ ]:
# A. What are the columns and index: do they suggest any relationship to other tables?

In [ ]:
# B. How many rows of data are there?

In [ ]:
# C. What are the types of each column?

In [ ]:
# 4.4 Boolean Filtering
# Let's return to the orders dataset for the rest of the challenges
# Use boolean filtering and DataFrame/DataSeries methods to solve the following challanges:

In [ ]:
# A. What is the mean profit of orders where the ship_mode is "Second Class"

In [ ]:
# B. Which product is the most commonly ordered on 2017-06-08

In [ ]:
# 4.5 Sorting and Filtering

In [ ]:
# A. What are the three most profitable orders purchased by customer PO-8865?

In [ ]:
# B. What are the five orders of product_id TEC-HEW-10002304 with the highest quanitity?

## Recap

We covered a lot of ground! It's ok if this takes a while to gel.

```python

# basic DataFrame operations
df.head()
df.tail()
df.shape
df.columns
df.Index

# selecting columns
df.column_name
df['column_name']

# renaming columns
df.rename({'old_name':'new_name'}, inplace=True)
df.columns = ['new_column_a', 'new_column_b']

# notable columns operations
df.describe() # five number summary
df['col1'].nunique() # number of unique values
df['col1'].value_counts() # number of occurrences of each value in column

# filtering
df[ df['col1'] < 50 ] # filter column to be less than 50
df[ (df['col1'] == value1) & (df['col2'] > value2) ] # filter column where col1 is equal to value1 AND col2 is greater to value 2

# sorting
df.sort_values(by='column_name', ascending = False) # sort biggest to smallest

```


It's common to refer back to your own code *all the time.* Don't hesistate to reference this guide! 🐼